# Generated by Django 5.2.11 on 2026-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, default='', max_length=400, verbose_name='Pod sarlavha')),
                ('cta_text', models.CharField(default="Ko'rish", max_length=80, verbose_name='Tugma matni')),
                ('image', models.ImageField(blank=True, help_text='Ixtiyoriy. Bo‘lmasa faqat matn va gradient ko‘rinadi.', null=True, upload_to='banners/', verbose_name='O‘ng tomondagi rasm')),
                ('bg_color_start', models.CharField(default='#0078FF', max_length=32, verbose_name='Gradient boshlanishi (hex)')),
                ('bg_color_end', models.CharField(default='#004aad', max_length=32, verbose_name='Gradient tugashi (hex)')),
                ('target', models.CharField(choices=[('none', 'Hech qayerga'), ('explore', 'Xarita (Explore)'), ('favorite', 'Sevimlilar'), ('home', 'Bosh sahifa'), ('external', 'Tashqi havola')], default='none', max_length=20, verbose_name='Tugma bosilganda')),
                ('link_url', models.URLField(blank=True, default='', help_text='Faqat «Tashqi havola» tanlanganida ishlatiladi.', max_length=500, verbose_name='Tashqi havola')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo banner',
                'verbose_name_plural': 'Promo bannerlar',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
