# Generated by Django 5.2.11 on 2026-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Upload o‘rniga to‘g‘ridan-to‘g‘ri rasm linki ham berish mumkin.', max_length=800, verbose_name='Banner rasmi URL'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Ixtiyoriy. To‘liq banner rasmi yuklansa karuselda ko‘rinadi.', null=True, upload_to='banners/', verbose_name='Banner rasmi (upload)'),
        ),
    ]
