# Generated by Django 5.2.11 on 2026-03-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_promobanner_image_url_alter_promobanner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promobanner',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Ixtiyoriy. Bo‘lmasa faqat matn va gradient ko‘rinadi.', null=True, upload_to='banners/', verbose_name='O‘ng tomondagi rasm'),
        ),
    ]
