# Generated by Django 5.2.11 on 2026-03-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_google_maps_url_gym_images_gym_yandex_maps_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['-rating'], 'verbose_name': 'Zal (Gym)', 'verbose_name_plural': 'Zallar (Gyms)'},
        ),
        migrations.AlterField(
            model_name='gym',
            name='accent_color',
            field=models.CharField(blank=True, default='#0078FF', max_length=80, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='district',
            field=models.CharField(max_length=120, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='entry_price',
            field=models.IntegerField(default=0, verbose_name="Kirish narxi (so'm)"),
        ),
        migrations.AlterField(
            model_name='gym',
            name='facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='Imkoniyatlar'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='google_maps_url',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Google Maps havolasi'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='gradient',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fon gradient'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='hours',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Ish vaqti'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='images',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='gym',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Ochiqmi?'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Kenglik (lat)'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='lng',
            field=models.FloatField(default=0, verbose_name='Uzunlik (lng)'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='monthly_price',
            field=models.IntegerField(default=0, verbose_name="Oylik narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Zal nomi'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='region',
            field=models.CharField(blank=True, default='Toshkent viloyati', max_length=120, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Sharhlar soni'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='sports',
            field=models.JSONField(blank=True, default=list, verbose_name='Sport turlari'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='yandex_maps_url',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Yandex Maps havolasi'),
        ),
        migrations.CreateModel(
            name='GymImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gyms/gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Izoh (ixtiyoriy)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqam')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='gyms.gym', verbose_name='Zal')),
            ],
            options={
                'verbose_name': 'Zal rasmi',
                'verbose_name_plural': 'Zal rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
