# Generated by Django 5.2.11 on 2026-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_gym_options_alter_gym_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, help_text="Avtomatik to'ldiriladi", max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text="Masalan: 💪 yoki 'gym', 'yoga', 'boxing'", max_length=80, verbose_name='Ikonka (emoji yoki key)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zal kategoriyasi',
                'verbose_name_plural': 'Zal kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gym',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='gyms', to='gyms.gymcategory', verbose_name='Kategoriyalar'),
        ),
    ]
