# Generated by Django 5.2.11 on 2026-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gymrating_gymview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sharh va baho', 'verbose_name_plural': 'Sharhlar va baholar'},
        ),
        migrations.AddField(
            model_name='gymrating',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Foydalanuvchi qoldirgan sharh matni', verbose_name='Izoh (sharh)'),
        ),
    ]
