# Generated by Django 5.2.11 on 2026-03-27 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gym_telegram_instagram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_gyms', to=settings.AUTH_USER_MODEL, verbose_name='Yoqtirgan foydalanuvchilar'),
        ),
    ]
