# Generated by Django 5.2.11 on 2026-03-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_gym_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
