# Generated by Django 5.2.11 on 2026-03-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Yuborish uchun Xabar', 'verbose_name_plural': '1. Yuborish uchun Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'verbose_name': "2. Qabul qiluvchi (Kim o'qidi?)", 'verbose_name_plural': '2. Qabul qiluvchilar (Hisobot)'},
        ),
    ]
